import argparse
import json
from collections import defaultdict


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Extract one given species from given synteny map file.",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('-infile',
                        type=str,
                        nargs='?',
                        dest='infilename',
                        help='json synteny map file generated by orthodb_query.py')
    parser.add_argument('-outfile',
                        type=str,
                        nargs='?',
                        dest='outfilename',
                        help='json output filename')
    parser.add_argument('-species',
                        type=str,
                        nargs='?',
                        dest='species',
                        help='species name')
    args = parser.parse_args()
    with open(args.infilename, 'r') as infile:
        mapping = json.load(infile)
    new_dict = defaultdict(list)
    for key, value in mapping.items():
        for record in value:
            new_dict[key] += record.get(args.species, [])
    with open(args.outfilename, 'w') as outfile:
        json.dump(new_dict, outfile)
